[build]
  publish = "."
  command = ""

[[headers]]
  for = "/data/*.geojson"
  [headers.values]
    Content-Type = "application/geo+json; charset=utf-8"
    Cache-Control = "public, max-age=300"

[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=300"
